### ISSUE TITLE
Reduce CSS Specificity

### ISSUE THREAD

**Issue by iamntz** [pojome/elementor#1184]
```css
.elementor-accordion .elementor-accordion-title .elementor-accordion-icon {}
```
vs

```css
.elementor-accordion-icon {}
```

This is just an example, there are quite a few selectors that are harder to override and the overall size tend to increase.

**Comment by arielk** [comment]
Today we have been working according to the concept of BEM, you can read about it here: http://getbem.com/

It will take some time but in the end everything will go by BEM. Thanks for your feedback.

**Comment by joshmarom** [comment]
You need to keep in mind that one of the challenges we face when styling Elementor elements, is making sure that they will not be corrupted by the theme's CSS.
In many cases that requires very specific selectors that will not be overridden by the theme.

**Comment by iamntz** [comment]
> You need to keep in mind that one of the challenges we face when styling Elementor elements

Right, but the main idea is to match Elementor to the site, not the other way around, no?

**Comment by joshmarom** [comment]
Imagine you have a widget that outputs a `<ul>` list with `<li>` items inside it. (for example, the Price List widget)
Now imagine the theme has a css rule like:
```css
.entry-content li {
    margin: 0 0 0 36px; 
}```
Imagine the same theme also has another rule:
```css
.entry-content ull {
    list-style: disc outside;
}
```
Should we let the theme mess up the widget or the other way around?
