### ISSUE TITLE
White background behind (pro) portfolio and alike

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#1783]
Just wanted to change some thinks on my website, so i found a white background behind some elementor widgets, seems to be widgets like the portfolio widget. 

You can look it up at http://stefaneduardkrenn.com/ 
At the main page, there are blog and portfolio element with a white background, also the portfolio itself on a different page got the white background.

When i try to change the background, a second one appears - but slightly offset. 

Does anyone of you have the same problem? Seems it appears after a update or after some time, wasn't like this when i made it. 

thanks, steven

**Comment by carasmo** [comment]
That is part of your theme. The class .entry has a background color of white. It has nothing to do with Elementor.

**Comment by joshmarom** [comment]
Like @carasmo diagnosed correctly, your theme gives a white background color to every element with the class `.entry`.

A simple fix would be to add a custom CSS rule to the widget:
```css
selector .entry {
    background-color: transparent;
}
```
Or add this rule globally to your entire site:
```css
.elementor .entry {
    background-color: transparent;
}
```
