### ISSUE TITLE
No Masonry Grid on Image Galleries

### ISSUE THREAD

**Issue by WinstonGFX** [pojome/elementor#2142]
The Pro feature list indicated that a masonry grid layout would be available when upgraded, but it seems that the masonry format only works with "Post" widgets, but not the "Image Gallery" widget. I'm hoping that this functionality can be added to the "Image Gallery" widget for added flexibility of gallery layouts.

**Comment by Jaska** [comment]
This! Other way to do this could be to just add image-gallery as an option for the Post widget.

**Comment by IDESIGNSTUDIO** [comment]
I second the feature requests here. Indeed, using Elementor Pro to work on different client projects, I found the lack of more flexible features, related to image show-offs,  to get the desired designs. 

So feature requests:

1. Add **masonry** in Gallery Widget - with 2 visual options: masonry by row, masonry by column

2. Add **masonry** in Portfolio Widget - with 2 visual options: masonry by row, masonry by column

3. Add new design layout option for Posts Widget - post title / post meta / excerpt to be shown in an overlay above the image, when Image Position is 'Top', on mouse hover. 

Thanks!
Always happy to work with Elementor!

**Comment by Hunuke** [comment]
Same here. Two or more images with different sizes look terrible in one row.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by drawcard** [comment]
As a workaround, take a look at this video: https://www.youtube.com/watch?v=g7hQ7AMEmjA

Quoting from the pinned author comment, here's the necessary code:

```css
Updated code, which will allow you to adjust gaps between images from the Widget > Style Tab and to set Mobile responsiveness :  

.gallery-icon img{
    width: 100%;
}
@media (min-width: 1024px) {
    #gallery-1 {
      column-count: 4;
      column-gap: 0px;
    }
}
@media (min-width:361px) and (max-width:1024px) {
    #gallery-1 {
      column-count: 3;
      column-gap: 0px;      
    }  
}
@media (max-width:360px) {
    #gallery-1 {
      column-count: 3;
      column-gap: 0px;      
    }  
}﻿
```
