### ISSUE TITLE
Center align animated headline

### ISSUE THREAD

**Issue by Roderiquez** [pojome/elementor#2515]
Hi guys,

I'm currently using the great animated headline feature. I would like to center align the words in my animation on mobile to make it look neat, but it doesn't seem to align each word independently.

Instead it center-aligns the whole batch, making smaller and longer words appear off-center.

Is this something you can fix?

Best regards,
Rod

**Comment by joshmarom** [comment]
Hi @Roderiquez 
Try adding this code in the widget's custom CSS panel:
```css
selector .elementor-headline-dynamic-wrapper {
    text-align: center;
}
```
Let me know if that does the trick.

**Comment by Phil1137** [comment]
When I center align the text with the above-mentioned CSS code the animation now seems to show up awkwardly. Is there a fix for that?

**Comment by IMTanuki** [comment]
FWIW, I found that this issue occurs only when using rotating text AND clip animation.
- with clip, it seems that the center alignment is calculated for **each** instance of text in the rotating text list (or at least, it sure looks a lot better)
- the default clip cursor color is a bit stark, so the following CSS can white it out:

.elementor-headline-animation-type-clip .elementor-headline-dynamic-wrapper:after {
    background-color: **white;**
}

**Comment by leolll** [comment]
This bug still occurs when you center align rotating text.  My solution based on @joshmarom's code was:
```css
.elementor-headline--style-rotate .elementor-headline-dynamic-wrapper {
    text-align: center;
}
```
