### ISSUE TITLE
Maintenance page conflict with All in One SEO Pack Plugin - no page background image

### ISSUE THREAD

**Issue by Semogj** [pojome/elementor#2717]
Hello, I found a possible conflict with All in One SEO plugin that made me scratch my head for half an hour until I decided to hammer it in the CSS.

## Description
I am working on a new website and I am using the "coming soon" maintenance mode of Elementor for displaying a static page with a whole page background 

The page background is set by elementor on the body HTML tag through the following CSS:

```css
body.elementor-page-795 {
    background-color: #333333;
    background-image: url(http://youthcoop.pt/wp-content/uploads/2017/11/pexels-photo-241044-1.jpeg);
    background-repeat: no-repeat;
    background-size: cover;
}
```
Without All In One SEO Pack plugin activated, the page HTML looks like this:

```html
<body class="elementor_library-template elementor_library-template-elementor_canvas single
 single-elementor_library postid-795 custom-background wp-custom-logo youthcoop
 elementor-maintenance-mode elementor-default elementor-page **elementor-page-795**"
 data-elementor-device-mode="desktop">
</body>
```

All In One SEO Pack activated (without any configuration) besides setting the option to "static front page":

```html
<body class="elementor_library-template elementor_library-template-elementor_canvas single 
single-elementor_library postid-795 custom-background wp-custom-logo youthcoop
elementor-maintenance-mode elementor-default" data-elementor-device-mode="desktop">
</body>
```
The class **elementor-page-795** is missing from the body and the page do not display the background. **This only happens on the maintenance page!** If accessed directly the page shows up correctly!

Note: I also tested with Twenty Seventeen theme.

## Steps to reproduce

1. Set up a coming soon page in elementor that uses a full page background. Make sure the page model is configured to "Elementor Canvas"!
2. Activate coming soon mode.
3. Install and enable All in One SEO Pack plugin (https://pt.wordpress.org/plugins/all-in-one-seo-pack/)
4. Observe the page without background.

## Environment

https://pastebin.com/TtFw8Gy5

Thanks!

------------
Normal:
![normal](https://user-images.githubusercontent.com/147530/32606097-e227bdb6-c54b-11e7-8a55-c7fe10b26c63.jpg)
With All in One SEO Pack:
![with all in one seo pack](https://user-images.githubusercontent.com/147530/32606096-e20ac49a-c54b-11e7-8533-a769b1b4a862.jpg)

**Comment by bainternet** [comment]
@Semogj 

Thanks for reporting this, we can replicate and we have an idea what the cause.

For now, a simple fix would be to define background using  "custom CSS" in the maintenance mode template with just body as the selector.  for example if your css is:

``` css
body.elementor-page-795 {
    background-color: #333333;
    background-image: url(http://youthcoop.pt/wp-content/uploads/2017/11/pexels-photo-241044-1.jpeg);
    background-repeat: no-repeat;
    background-size: cover;
}
```

then use:
``` css
body {
    background-color: #333333;
    background-image: url(http://youthcoop.pt/wp-content/uploads/2017/11/pexels-photo-241044-1.jpeg);
    background-repeat: no-repeat;
    background-size: cover;
}
```
