### ISSUE TITLE
BUG: I can't use point on price table

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#2947]
Look:

http://prntscr.com/hn1053

**Comment by bainternet** [comment]
@silvioghedin 

Elementor splits the price to give you more control over the styling, but if you want to add the decimal comma, you can use this CSS:

```CSS
span.elementor-price-table__integer-part:after {
    content: ".";
}
```
