### ISSUE TITLE
Mobile video background

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#3020]
In mobile view why full height section is restricted?Isn't full height is supposed for all devices or except mobile device? Due to this cause full height doesn't work in mobile desvice?

```CSS
@media (min-width: 768px){
    .elementor-section.elementor-section-height-full {
        height: 100vh;
    }
}
```
