### ISSUE TITLE
Bug: mobile Nav Menu will not right align on some displays

### ISSUE THREAD

**Issue by icecandy** [pojome/elementor#3161]
I cannot get the Nav Menu icon  (the hamburger icon) on mobile to right align on some screens, specifically the iPhone 6 and 7.
This is with the alignment set to right align. You can see this on my current site www.icecandy.com.
I have tried many different variations and work arounds to no avail.
On my icecandy.com site I also have a logo top left of the header, but if I test with just the Nav Menu and set a border one can see very clearly that the width of the widget is the full width of the screen ie the border extends to the far left and right of the header. It should only be about 40 pixels wide roughly. This is obviously wrong. Changing the padding of the widget makes no difference. I am attaching a screen grab from an iPhone 6 (simulator).

![simulator screen shot 12 jan 2018 16 27 11](https://user-images.githubusercontent.com/929997/34884750-9b649272-f7b5-11e7-8850-eb4864ce2f30.png)

**Comment by bainternet** [comment]
@icecandy 

Seems like an issue with old IOS/Safari and `margin-left/right : auto`.

You can force it to stick to the right on small devices using float ex:
```CSS
@media only screen and (min-device-width : 375px) and (max-device-width : 667px) {
    #widget-ID .elementor-widget-container{
        float: right;
    }
}
```
