### ISSUE TITLE
Background video alignment

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3327]
Hi, is there a way, how can I affect the background video alignment (eg. center center, top center, bottom center, ...)?
Thanks

**Comment by bainternet** [comment]
@black-eye 

the video background works differently than a background image so there is not `center center, top center.....` option.

Its set with CSS that defaults to:
```CSS
.elementor-background-video-container{
    height: 100%;
    width: 100%;
    top: 0;
    left: 0;
    position: absolute;
    overflow: hidden;
    z-index: 0;
    -webkit-transition: opacity 1s;
    -o-transition: opacity 1s;
    transition: opacity 1s;
}
```

So you can try overwriting this, playing with width, height, top and left.

Hope this helps.
