### ISSUE TITLE
section controls dissapear on mouse over, not accessible when using neg margins

### ISSUE THREAD

**Issue by joshallen73** [pojome/elementor#3346]
## Description

When using neg margin to push a section up a little, the section controls cant be clicked as they dissapear under the above section

## Steps to reproduce

set a neg margin for a section under a section to 100px
## Environment

 using the latest builds -google chrome

**Comment by dasigna** [comment]
seems quite related to this one #3291 :)

**Comment by bainternet** [comment]
To overcome this issue you create by using negative margins you need to set the margins via custom CSS and make sure it's not applied in edit mode:

```CSS
body:not(.elementor-editor-active) #my-section-id{ 
     margin-top: -100px;
}
```
