### ISSUE TITLE
Separate style

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#3849]
I am not sure if I missed anything.

Separate before is not working. only after is working.

![screenshot_765](https://user-images.githubusercontent.com/660572/37757888-12509606-2db7-11e8-9118-06b2405f4b43.png)

```CSS
.elementor-control.elementor-control-separator-after:after {
    content: "";
    position: absolute;
    height: 3px;
    width: 100%;
    bottom: 0;
    left: 0;
    background-color: #d5dadf;
}
````

It's too thick and not enough room ( margin or padding ) there.

Any reason or am I missing?

using Beta 2 3rd one. but I think it has been.
