### ISSUE TITLE
Blog Cards - Badge icon colour per category - feature request

### ISSUE THREAD

**Issue by rich73625** [pojome/elementor#4074]
Hi,
Could we have the option to style the Badge icon (in the Blog Card) so that we could set a specific colour for each category? (So a different colour icon will show depending on the Category it's in, or choose a "1st choice colour" for ones where there the post is in more than one category.
Thanks.

**Comment by bainternet** [comment]
@rich73625 

How would that be implemented? add a color control per each category on the site?

**Comment by rich73625** [comment]
Yes, I guess so. Could be a drop down menu in the style options for the card, (shows each category existing with a field next to it for the hex) or perhaps a separate control panel "somewhere" where you allocate the colour to the category.

**Comment by bainternet** [comment]
What would happen if you have 100s or 1000s of terms (tags, categories)??

seems to be getting messy real quick, when its fairly easy to do with custom css:

```CSS
.product_cat-music .elementor-post__badge { 
    background-color: #001122;
    color: #ffffff;
}

.product_cat-new .elementor-post__badge { 
    background-color: #221100;
    color: #000000;
}
```

Other then that, currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
