### ISSUE TITLE
Adding YouTube player sizing controls

### ISSUE THREAD

**Issue by tannerchung** [pojome/elementor#4556]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I'm trying to resize the YouTube widget as needed but it's impossible to do so unless I do some tricks like this: 

```CSS
selector {
    position: relative;
    height: 750px;
}

selector iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 750px;
}

selector .elementor-custom-embed-image-overlay {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 750px;
}
```

The problem is that this will cause the video to proportionally resize itself - I don't want this, I want something like this:  https://jsfiddle.net/cafevagrant/h3j2nbyz/

**Describe the solution you'd like**

I'd like the ability to change the YouTube videos dimensions with the `.youtube-player` class

**Describe alternatives you've considered**

See above
