### ISSUE TITLE
Tablet responsiveness

### ISSUE THREAD

**Issue by golamminoo** [pojome/elementor#4651]
Hi There,

I am one of the Elementor's Pro users. Sometimes I need to show for example a widget on desktop and hide it on tablet, Thanks Elementor I can achieve it perfectly! In that way, The hidden widget on tablet doesn't shown in both portrait and landscape views, But sometimes I want to hide a widget on tablet's portrait view and have it shown on Tablet's landscape view. How can I achieve that with CSS or any other way that you can advice me? I really appreciate you for that.

Is there any way to hide a widget or section JUST in tablet's portrait view and have it shown in tablet's landscape view?

Best Regards,
Ali

**Comment by bainternet** [comment]
@golamminoo 

You can with custom CSS and media query for tablet portrait:

something like:
```CSS
@media only screen 
  and (min-device-width: 768px) 
  and (max-device-width: 1024px) 
  and (orientation: portrait) 
  and (-webkit-min-device-pixel-ratio: 1) {
   #widget-id { 
         display:none;
    }
}
```
