### ISSUE TITLE
Reverse Mobile Drop-down menu order for Right to Left Languages

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#5553]
I have recently been trying to assist a new user, in the facebook group, who is creating a site in Hebrew. He is able to arrange the desktop menu so that the “Home” button is on the right-hand side of the menu as the ‘natural’ place for someone reading right to left. This can be achieved by placing it as the last item in the WordPress menu. This means, however, that “Home” appears at the bottom of the drop-down menu when viewed on a mobile. A solution was provided by David Beckwith to use a flex-box 
```CSS
@media (max-width: 768px) {
	.elementor-nav-menu__align-right .elementor-nav-menu {
		display: -webkit-box;
		display: -ms-flexbox;
		display: flex;
		-webkit-box-orient: vertical;
		-webkit-box-direction: reverse;
		-ms-flex-direction: column-reverse;
		flex-direction: column-reverse;
	}
}
```
As there are around eight languages that are written right to left it would be valuable to users writing in those languages a means of re-ordering the drop-down mobile menu.

I suggest that a setting value is added in Elementor>Settings>Advanced: “Reverse Mobile Menu” with a default of ‘No’ (see attached image). 
![reverse-menu](https://user-images.githubusercontent.com/22448787/44669366-9f658380-aa17-11e8-9ee2-1e708de1bb05.jpg)
