### ISSUE TITLE
Accordion & Toggle Widgets

### ISSUE THREAD

**Issue by kayola** [pojome/elementor#6949]
I would like to request the following options to improve the Accordion Widget:

- Hover options for Title Background color
- Border width options for TOP, RIGHT, BOTTOM & LEFT

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Hi @kayola 

Currently we do not support this feature but you can simply add Custom CSS in order to achieve this style:

for the accordion and toggles hover background:
```CSS
div.elementor-tab-title:hover {
    background: #00f7ac;
}
```

or for the borders:
```CSS
.elementor-accordion .elementor-accordion-item {
    border-width: 7px 1px 7px 1px;
    border-style: solid;
}
```

thanks.
